### PR TITLE
Stepping up to Python 2.7.12

### PR DESCRIPTION
**Pull request by cclauss**
Please make sure to check off these items before filing create a pull request:

- [x] Review the [steps for making a pull request](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/.github/CONTRIBUTING.md#making-a-pull-request)
- [ ] Reference the issue(s) your PR addresses
- [ ] Include screenshots and GIFs of when applicable

Check out the [Contributing Guidelines](https://github.com/IBM-Bluemix/logistics-wizard/blob/master/.github/CONTRIBUTING.md) for more detailed info

### CODE REVIEW

**Comment by jakepeyser** [comment]
Looking at the failed test, this breaks the environment variable lookup. Need to investigate further when you have some time.

**Comment by cclauss** [comment]
The error log says that when Travis fails, it is running Python 2.7.9 which is older than the 2.7.10 in your runtime.txt and the 2.7.12 in my runtime.txt.

https://github.com/IBM-Bluemix/logistics-wizard/blob/master/.travis.yml#L19-L20 Shows that we remove `.env.local` where `$SMTP_USER_NAME` is defined without sourcing it and then we source `.env`.

I can not figure how my change to runtime.txt caused this error.

**Comment by jakepeyser** [comment]
The `SMTP_USER_NAME` is defined as a Travis environment variable since the `.env.local` values are dummy template values. I am not sure on initial inspection, either. We will look when time permits

**Comment by jakepeyser** [comment]
The reason it is failing is because secure env vars are not available for pull requests where the origin of the pull request and the target repository are not the same [[source](https://blog.travis-ci.com/2013-06-10-secure-env-in-pull-requests/)]. I'm now seeing this issue in several PRs...

This means we need to skip tests that are dependent on these env vars whenever they don't exist. That would expose us a bit if people submit external PRs changing scripts like `messaging.py`. Anyone have ideas on how we might solve this issue?

cc: @rvennam @l2fprod @colbycheeze @LRRoberts0122

**Comment by jakepeyser** [comment]
#176 has been opened for this issue.

@cclauss: All that aside, we do not accept merges directly to the `master` branch. I will make the changes for #176 off of `dev` and update to 2.7.12 there, as well

**Pull request closed without merging**
